// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package debug

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FlamingoGrpcDebugClient is the client API for FlamingoGrpcDebug service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FlamingoGrpcDebugClient interface {
	Identify(ctx context.Context, in *IdentifyRequest, opts ...grpc.CallOption) (*IdentityResponse, error)
}

type flamingoGrpcDebugClient struct {
	cc grpc.ClientConnInterface
}

func NewFlamingoGrpcDebugClient(cc grpc.ClientConnInterface) FlamingoGrpcDebugClient {
	return &flamingoGrpcDebugClient{cc}
}

func (c *flamingoGrpcDebugClient) Identify(ctx context.Context, in *IdentifyRequest, opts ...grpc.CallOption) (*IdentityResponse, error) {
	out := new(IdentityResponse)
	err := c.cc.Invoke(ctx, "/FlamingoGrpcDebug/Identify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlamingoGrpcDebugServer is the server API for FlamingoGrpcDebug service.
// All implementations must embed UnimplementedFlamingoGrpcDebugServer
// for forward compatibility
type FlamingoGrpcDebugServer interface {
	Identify(context.Context, *IdentifyRequest) (*IdentityResponse, error)
	mustEmbedUnimplementedFlamingoGrpcDebugServer()
}

// UnimplementedFlamingoGrpcDebugServer must be embedded to have forward compatible implementations.
type UnimplementedFlamingoGrpcDebugServer struct {
}

func (UnimplementedFlamingoGrpcDebugServer) Identify(context.Context, *IdentifyRequest) (*IdentityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Identify not implemented")
}
func (UnimplementedFlamingoGrpcDebugServer) mustEmbedUnimplementedFlamingoGrpcDebugServer() {}

// UnsafeFlamingoGrpcDebugServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlamingoGrpcDebugServer will
// result in compilation errors.
type UnsafeFlamingoGrpcDebugServer interface {
	mustEmbedUnimplementedFlamingoGrpcDebugServer()
}

func RegisterFlamingoGrpcDebugServer(s grpc.ServiceRegistrar, srv FlamingoGrpcDebugServer) {
	s.RegisterService(&FlamingoGrpcDebug_ServiceDesc, srv)
}

func _FlamingoGrpcDebug_Identify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlamingoGrpcDebugServer).Identify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FlamingoGrpcDebug/Identify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlamingoGrpcDebugServer).Identify(ctx, req.(*IdentifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FlamingoGrpcDebug_ServiceDesc is the grpc.ServiceDesc for FlamingoGrpcDebug service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlamingoGrpcDebug_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FlamingoGrpcDebug",
	HandlerType: (*FlamingoGrpcDebugServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Identify",
			Handler:    _FlamingoGrpcDebug_Identify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "debug.proto",
}
